/* first time database setup */
USE yawning;

CREATE TABLE signups (
  email VARCHAR(50) UNIQUE,
  salt VARCHAR(50),
  hash VARCHAR(100),
  verify INTEGER DEFAULT 0
);

CREATE TABLE profiles (
  id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY UNIQUE,
  td TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  email VARCHAR(50) UNIQUE,
  salt VARCHAR(50),
  hash VARCHAR(100),
  lastToken INTEGER,
  username VARCHAR(50) NOT NULL DEFAULT '',
  firstname VARCHAR(50) NOT NULL DEFAULT '',
  lastname VARCHAR(50) NOT NULL DEFAULT '',
  biography VARCHAR(5000) NOT NULL DEFAULT ''
);
